# Generated by Django 5.2 on 2026-09-16 08:49

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='Please Check your email!',
        ),
        migrations.AlterField(
            model_name='participants',
            name='participation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2026, 9, 16, 9, 49, 13, 87247)),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('evt_date__gt', datetime.datetime(2026, 9, 16, 9, 49, 13, 85248))), name='Please Check your email!'),
        ),
    ]
